### ISSUE TITLE
form groups are missed aligned, probably due to changes on button/input sizes

### ISSUE THREAD

**Issue by nurv** [FenixEdu/ashes-theme#2]
Example:

![screen shot 2014-08-21 at 14 56 33](https://cloud.githubusercontent.com/assets/132118/3996984/0bac7006-293b-11e4-8c13-a6c33c60dfd1.png)

**Comment by jcarvalho** [comment]
This has been fixed in e184713e5a0307c473311d884e3aac0406bc255f.
